"""Tests for src/infrastructure/audio.py.

Verifies that SoundPlayer initialises without crashing and that all
play_* methods are callable regardless of whether pygame.mixer is
available. Sounds generated by the procedural engine are also checked
for correct buffer length and stereo/mono layout.
"""
import array
import math

import pygame
import pytest

from src.infrastructure.audio import SoundPlayer


def _init_player() -> SoundPlayer:
    pygame.init()
    return SoundPlayer()


class TestSoundPlayerInit:
    def test_creates_without_error(self) -> None:
        player = _init_player()
        assert isinstance(player, SoundPlayer)

    def test_ok_flag_set_when_mixer_available(self) -> None:
        player = _init_player()
        assert player._ok is True

    def test_channels_is_positive(self) -> None:
        player = _init_player()
        assert player._channels in (1, 2)

    def test_freq_is_positive(self) -> None:
        player = _init_player()
        assert player._freq > 0


class TestSoundPlayerPlayMethods:
    def test_play_card_does_not_raise(self) -> None:
        player = _init_player()
        player.play_card()

    def test_play_attack_does_not_raise(self) -> None:
        player = _init_player()
        player.play_attack()

    def test_play_block_does_not_raise(self) -> None:
        player = _init_player()
        player.play_block()

    def test_play_death_does_not_raise(self) -> None:
        player = _init_player()
        player.play_death()

    def test_play_end_turn_does_not_raise(self) -> None:
        player = _init_player()
        player.play_end_turn()

    def test_play_hit_does_not_raise(self) -> None:
        player = _init_player()
        player.play_hit()

    def test_play_win_does_not_raise(self) -> None:
        player = _init_player()
        player.play_win()


class TestSoundPlayerBuffer:
    def test_buf_mono_length(self) -> None:
        player = _init_player()
        samples = [0.5, -0.5, 0.0, 1.0]
        buf = player._buf(samples)
        assert len(buf) == len(samples) * player._channels

    def test_buf_clamps_to_int16_range(self) -> None:
        player = _init_player()
        buf = player._buf([2.0, -2.0])
        assert all(-32768 <= v <= 32767 for v in buf)

    def test_buf_zero_samples(self) -> None:
        player = _init_player()
        buf = player._buf([0.0] * 100)
        assert all(v == 0 for v in buf)

    def test_tone_returns_sound(self) -> None:
        player = _init_player()
        sound = player._tone(440, 100)
        assert sound is not None

    def test_sweep_returns_sound(self) -> None:
        player = _init_player()
        sound = player._sweep(440, 220, 150)
        assert sound is not None

    def test_no_op_when_ok_false(self) -> None:
        player = _init_player()
        player._ok = False
        player.play_card()   # must not raise
        player.play_attack()
